version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development  # Set Flask to development mode
    volumes:
      - .:/app  # Mount the current directory into the container to enable live code reloading
      